### ISSUE TITLE
Memory usage increases proportionally to number of rounds

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fastchess#506]
even with no book

**Comment by Disservin** [comment]
match are created at the beginning, the more rounds the more matches, the more matches memory memory, by how much?

**Comment by gahtan-syarif** [comment]
this is with `-rounds 1000000` and no book, so it seems 240 bytes per game?

![Screenshot 2024-06-25 142145](https://github.com/Disservin/fast-chess/assets/155860115/70c43dff-ede8-41f2-acf6-cb9f88ecfac8)

**Comment by gahtan-syarif** [comment]
cutechess with the same rounds is ~30MB

**Comment by gahtan-syarif** [comment]
fixed with https://github.com/Disservin/fastchess/commit/6134e181893b852b8f89a257e7f10cb09b4d7e13
