### ISSUE TITLE
Increase unit test coverage

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fastchess#511]
should be added:
- fastchess output
- cutechess output ✅ 
- epdbuilder ✅ 
- game adjudication ✅ 
- uci options tests
- config parsing tests
- setResult tests
- matchGenerator tests

**Comment by gahtan-syarif** [comment]
game adjudication and cutechess output pretty much covered with commit https://github.com/Disservin/fast-chess/pull/581

**Comment by Disservin** [comment]
some other parts should also get a test, i.e. the uci options classes and the config parsing lacks also some tests i think + the result loading test needs to be reimplemented

**Comment by Disservin** [comment]
ill close this for now a bit redundant

**Comment by Disservin** [comment]
[coverage.zip](https://github.com/user-attachments/files/17169033/coverage.zip)

btw here is a coverage report if you are interested, just open the coverage.html, still more things to cover :D

if you want to generate this just make these changes
```diff
diff --git a/app/Makefile b/app/Makefile
index a07fb60..e0991ee 100644
--- a/app/Makefile
+++ b/app/Makefile
@@ -12,7 +12,7 @@ INCDIR           := src
 
 #Flags, Libraries and Includes
 CXXFLAGS         := -O3 -std=c++17 -Wall -Wextra -DNDEBUG
-CXXFLAGS_TEST   := -O2 -std=c++17 -Wall -Wextra -pedantic -Wuninitialized -g3 -fno-omit-frame-pointer
+CXXFLAGS_TEST   := -O0 --coverage -g -std=c++17 -Wall -Wextra -pedantic -Wuninitialized -g3 -fno-omit-frame-pointer
 INC              := -I$(INCDIR) -Ithird_party
 
 SRC_FILES        := \
```

and then install https://github.com/gcovr/gcovr, and run the tests and then run `gcovr --html-details coverage.html` and it will create the html files

**Comment by Disservin** [comment]
![image](https://github.com/user-attachments/assets/d6b39261-2b6e-41cc-8414-d37bfc785b00)

**Comment by gahtan-syarif** [comment]
oh wow i didnt know this was a thing, pretty cool lol

**Comment by Disservin** [comment]
a cheap way to get high test coverage is to generate a config, and just invoke the program inside the unit test basically, and then catch the stdout like this https://stackoverflow.com/questions/4191089/how-to-unit-test-function-writing-to-stdout-stdcout if you want to check something isn't the greatest but gets the coverage high up and we can write different configs which cover all code paths actually
