### ISSUE TITLE
Wb2Uci engines not working

### ISSUE THREAD

**Issue by AlexBrunetti** [Disservin/fastchess#524]
Hi,
Is this an expected/intentional behavior, or is it an issue that has never been addressed?
Thanks,
Alex

**Comment by Disservin** [comment]
no should work.. id need to the see log in that case (`-log file=log.txt level=trace`)

**Comment by AlexBrunetti** [comment]
Thanks for your answer. You can find Fastchess logs for some Wb2Uci engines, cutechess logs and a sample engine [here](https://e4e6.com/max/).

Alex

**Comment by Disservin** [comment]
mhh dunno this doesn't look like an issue from me, 
```
[Engine] [22:31:12.691648] <  2> Myrddin 0.90 Wb2Uci ---> uciok
[TRACE ] [22:31:12.691824] <  2> fastchess --- Sending ucinewgame to engine Myrddin 0.90 Wb2Uci
[Engine] [22:31:12.691836] <  2> Myrddin 0.90 Wb2Uci <--- ucinewgame
[TRACE ] [22:31:12.691848] <  2> fastchess --- Pinging engine Myrddin 0.90 Wb2Uci
[Engine] [22:31:12.691855] <  2> Myrddin 0.90 Wb2Uci <--- isready
[Engine] [22:31:12.691976] <  2> Myrddin 0.90 Wb2Uci ---> info string Error starting engine.
[TRACE ] [22:31:12.692574] <  2> fastchess --- Engine Myrddin 0.90 Wb2Uci is responsive.
[TRACE ] [22:31:12.692587] <  2> fastchess --- Sending setoption to engine Myrddin 0.90 Wb2Uci Hash 128
[Engine] [22:31:12.692596] <  2> Myrddin 0.90 Wb2Uci <--- setoption name Hash value 128
[TRACE ] [22:31:12.692607] <  2> fastchess --- Failed to send setoption to engine Myrddin 0.90 Wb2Uci Hash 128
[TRACE ] [22:31:12.692615] <  2> fastchess --- Sending ucinewgame to engine Myrddin 0.90 Wb2Uci
```
the engine just dies somewhere between ucinewgame and isready

**Comment by AlexBrunetti** [comment]
Yes. This issue occurs with all Wb2Uci engines, but only in Fastchess. Where should I look to find the problem? :)

Alex

**Comment by gahtan-syarif** [comment]
> Yes. This issue occurs with all Wb2Uci engines, but only in Fastchess. Where should I look to find the problem? :)
> 
> Alex

does this work in cutechess where you set `proto=uci` ? if so, maybe we can see the log output when using cutechess to see if theres any differences?

**Comment by AlexBrunetti** [comment]
Sure, everything is included in the zip file

Alex

**Comment by AlexBrunetti** [comment]
Partially solved: the issue was that the working directory needs to be set correctly because Wb2Uci engines require support files. However, the setting dir="" does not seem to work.

Alex

**Comment by Disservin** [comment]
goood catch, thanks.

**Comment by Disservin** [comment]
Doesn't work on linux/mac right now, see https://github.com/Disservin/fastchess/issues/699.
