### ISSUE TITLE
CI builds doesnt show git SHA

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fastchess#665]
makes it hard to differentiate the dev versions

**Comment by Disservin** [comment]
they dont show because they are release builds https://github.com/Disservin/fastchess/commit/b94f685dfc7587aa62bb7c6e6c3bc189f7ca3d56

**Comment by Disservin** [comment]
I also take the release binaries straight from the ci..

**Comment by gahtan-syarif** [comment]
> they dont show because they are release builds [b94f685](https://github.com/Disservin/fastchess/commit/b94f685dfc7587aa62bb7c6e6c3bc189f7ca3d56)

If so then maybe the git sha can be shown for the release builds as well?

**Comment by Disservin** [comment]
which we didnt want to have to differentiate between release and non release
