### ISSUE TITLE
missing comma in pgn

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fastchess#702]
cutechess:
`Qb6 {0.00/23 0.22s, Draw by adjudication} 1/2-1/2`

fastchess:
`Ke4 {-6.31/11 0.005s White wins by adjudication} 1-0`

fastchess is missing the comma before the "White wins by adjudication". unsure if this affects pgn parsing

**Comment by Disservin** [comment]
yea we should add the comma
