### ISSUE TITLE
Accepts and Regurgitates Invalid Promotion `bestmove` String

### ISSUE THREAD

**Issue by jw1912** [Disservin/fastchess#705]
#### Description
If an engine outputs a promotion bestmove with the promotion a capital letter, e.g. "a7a8Q", fastchess (specifically the chess lib) will accept this as valid, and take this string and add it to the move list. This move will then be regurgitated to other engines in the UCI `position ... moves ...` command, many of which will fail to parse it properly and hence lead to strange/erroneous behaviour.

It isn't exactly clear, but the UCI spec seems to suggest that only lower case letters should be allowed.

#### Steps to Reproduce
1. Download [Midnight v9](https://github.com/archishou/MidnightChessEngine/releases/tag/v9)
2. Download [akimbo v1.0.0](https://github.com/jw1912/akimbo/releases/tag/v1.0.0)
3. Play a set of games using fastchess

#### Fix Options: <https://github.com/Disservin/fastchess/blob/master/app/src/matchmaking/match/match.cpp#L248>
1. Convert bestmove strings to lower case
2. Disallow moves with upper case letters

**Comment by gahtan-syarif** [comment]
Good idea to sanitize the engine moves before passing it to the opposing engine
Mid from stockfish discord encountered a similar issue a while ago where his engine spaghet outputted a null terminator at the end of his uci move, fastchess/chesslib was able to process the move just fine but stockfish fails to process it properly causing it to illegal move

**Comment by Disservin** [comment]
rather just take the chess::Move from the line below and convert that back to a uci move which is then appended to the position input,
