### ISSUE TITLE
weird man formatting in windows

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fastchess#711]
looks like this
![Screenshot 2024-09-27 032502](https://github.com/user-attachments/assets/d6452397-dcd1-482b-99f1-92d71de3dec6)

**Comment by Disservin** [comment]
yeah needs a ANSI-compatible UTF-8 terminal

**Comment by gahtan-syarif** [comment]
Oh im using windows cmd

**Comment by Disservin** [comment]
regardless, can you check if this makes it behave nicer? https://github.com/Disservin/fastchess/issues/711

**Comment by Disservin** [comment]
okay was able to check for myself it doesnt quite, i guess cmd just doesnt support this

**Comment by Disservin** [comment]
seems to work fine for me now with the pr

![image](https://github.com/user-attachments/assets/8358b93d-07ff-4920-9a3d-fea86f91c32a)

**Comment by gahtan-syarif** [comment]
ahh ok ill check

**Comment by gahtan-syarif** [comment]
works for me too 👍

**Comment by gahtan-syarif** [comment]
although i now notice that theres some bulletpoints that are not indented properly, like this san lan and uci
![Screenshot 2024-09-27 041527](https://github.com/user-attachments/assets/f1471ecc-1ac2-4d8c-b18f-ca5564bd8f23)

**Comment by Disservin** [comment]
Probably worth to open as a bug in lowdown ig if something like this doesn't already exist there. But I'm fine with it

**Comment by Disservin** [comment]
> although i now notice that theres some bulletpoints that are not indented properly, like this san lan and uci

fixed in https://github.com/Disservin/fastchess/commit/7ab3ce2cdd0d956f774be602fabbde6e1cc6729f
