### ISSUE TITLE
unable to load from config for multiple engines tournament

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fastchess#729]
it gets stuck like this:
![Screenshot 2024-10-02 041654](https://github.com/user-attachments/assets/9664b058-e9e0-407b-b42f-7263995e9370)

**Comment by Disservin** [comment]
mh couldnt reproduce

**Comment by Disservin** [comment]
now can

**Comment by gahtan-syarif** [comment]
tried it again and it worked, closing this issue

**Comment by Disservin** [comment]
mh it only works when all games have been played or none

**Comment by gahtan-syarif** [comment]
ah wait, loaded games now start from game 1 again
![Screenshot 2024-10-02 050257](https://github.com/user-attachments/assets/905e574e-a2da-457e-8114-86b66f6a7902)

**Comment by Disservin** [comment]
this here is wrong https://github.com/Disservin/fastchess/blob/master/app/src/matchmaking/tournament/roundrobin/match_generator.hpp#L39

**Comment by Disservin** [comment]
in general we need some additional logic to figure out where to start from, i think, we can't easily do this, because we dont know from which rounds the games are from, it would need some checking for each engine where it left off

**Comment by Disservin** [comment]
easiest for now just disable it

**Comment by gahtan-syarif** [comment]
i think its ok for the save feature to not be available in the multi engine tournaments, since its most useful for sprts
