### ISSUE TITLE
Cannot run shell script engines on Ubuntu

### ISSUE THREAD

**Issue by JeffreyEnglish** [Disservin/fastchess#745]
I'm running fastchess on a Ubuntu virtual machine. I've set up a shell script to run an engine in a python file

`python /home/azureuser/chess/engines/engine.py`

Running the command

`fastchess -engine cmd=engine.sh name="A" -engine cmd=engine.sh name="B" -each tc=5+3` gives me the error:
> Warning: Cannot start engine A:
> Cannot execute command: engine.sh

I've confirmed that the engine works by playing it in the cutechess GUI locally. I also confirmed that running engine.sh works and lets me interact with the engine through the command line.

Is there some permission or setting I am missing to get this working?

**Comment by Disservin** [comment]
Your bash script needs a shebang line
