### ISSUE TITLE
ending match based on SPRT result

### ISSUE THREAD

**Issue by jdart1** [Disservin/fastchess#747]
It would be nice to have an option to terminate the match early once the SPRT shows a significant result.

**Comment by gahtan-syarif** [comment]
For sprt the termination happens when you reach 95% confidence by default, you can change this by specifying the alpha and beta parameters

**Comment by Disservin** [comment]
yeah @gahtan-syarif is right not sure what you are trying to do?

**Comment by jdart1** [comment]
Ok, no problem, seems this feature is already there.

**Comment by Disservin** [comment]
it is basically the whole reason of sprt :D
